### ISSUE TITLE
It's not server-side rendering properly

### ISSUE THREAD

**Issue by stowball** [ButterCMS/react-ssr-example#1]
While the code is rendered in index.html without JS, when JS loads, it completely refreshes the component (you can see the flash), thus losing the point of server-side rendering.

The console has the following error about this:

```
index.js:2278 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <noscript data-reacti
 (server) <div data-reactid=".2
```

**Comment by fatihayyildiz** [comment]
Hi,

This answer is solving this problem [here](https://stackoverflow.com/questions/33521047/warning-react-attempted-to-reuse-markup-in-a-container-but-the-checksum-was-inv). I tried to create pull request but didn't have permission.

**Comment by jakelumetta** [comment]
@fatihayyildiz Sorry about that. Could you fork this repo and open a PR from your fork? We'd be happy to take a look.

**Comment by fatihayyildiz** [comment]
@jakelumetta I already did it at this repo : [SSR-Repo-Fork](https://github.com/fatihayyildiz/react-ssr-example). I just wrap the react string of element that is returning as a response. React.render wrap element issue is detailed this answer: [SSR Wrap react element answer](https://stackoverflow.com/a/33521172/4153009)

**Comment by jakelumetta** [comment]
@fatihayyildiz awesome thanks. Just merged it in. Resolved by https://github.com/ButterCMS/react-ssr-example/pull/4
