### ISSUE TITLE
json-loader needed when npm start

### ISSUE THREAD

**Issue by fomenyesu** [ButterCMS/react-ssr-example#5]
Hi,
I run "npm install & npm start" the project and it turns out Json-loader needed to start.

I fixed it on my fork: [commit a52e738c7767d044fa023ec8a00ed3fb4d313a4f](https://github.com/fomenyesu/react-ssr-example/commit/a52e738c7767d044fa023ec8a00ed3fb4d313a4f)
may I PR it?

**Comment by DaftVadeR** [comment]
This helped me with the same issue. Thanks man.

**Comment by jakelumetta** [comment]
@fomenyesu Yes, thanks!

**Comment by fomenyesu** [comment]
@jakelumetta  I already did it at this repo : [react-ssr-example](https://github.com/fomenyesu/react-ssr-example). I just update webpack config , json-loader needed in package.json file.

Thank you for the repo to help me learn the react ssr !
